# Generated by Django 3.0.5 on 2020-05-16 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveIntegerField(help_text='Values from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.PositiveIntegerField(help_text='Values from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Grade'),
        ),
    ]
